language: swift
script: xcodebuild -project AsyncAwait.xcodeproj -scheme AsyncAwait -destination platform\=OS\ X,arch\=x86_64 build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO TRAVIS=1 | xcpretty && exit ${PIPESTATUS[0]}
xcode_destination: platform=OS X,arch=x86_64
osx_image: xcode10
addons:
  homebrew:
    packages:
    - carthage
before_install:
  - carthage bootstrap --no-use-binaries